- hosts: all

  tasks:
    - name: Setup and Install Golang
      shell: |
        apt update
        apt upgrade
        wget https://dl.google.com/go/go1.13.5.linux-amd64.tar.gz
        tar -C /usr/local/ -xzf go1.13.5.linux-amd64.tar.gz
        echo "export PATH=$PATH:/usr/local/go/bin" >> $HOME/.profile
        source .profile
        go version
      register: command_output
      
    - name: Setup Gleam
      shell: |
        git clone https://github.com/chrislusf/gleam.git
        cd ./gleam/distributed/gleam
        go build .
      register: command_output

    - name: Start Gleam Master Node
      shell: |
        ./gleam master --address=":45326"
      register: command_output

    - name: Start Gleam Agent Nodes
      shell: |
        ./gleam agent --dir=2 --port 45327 --host=127.0.0.1
        ./gleam agent --dir=3 --port 45328 --host=127.0.0.1
      register: command_output

    - debug:
        var: command_output.stdout_lines